//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSPortal.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codelkup
    {
        public string LISTNAME { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Short { get; set; }
        public string Long { get; set; }
        public string Notes { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddWho { get; set; }
        public System.DateTime EditDate { get; set; }
        public string EditWho { get; set; }
        public string TrafficCop { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
