//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSPortal.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class LotxLocxId : ViewInformation
    {
        public Nullable<int> Gennumber { get; set; }
        public string WarehouseKey { get; set; }
        public string Lot { get; set; }
        public string Loc { get; set; }
        public string Id { get; set; }
        public string StorerKey { get; set; }
        public string Sku { get; set; }
        public string SkuDescription { get; set; }
        public int Qty { get; set; }
        public int QtyAllocated { get; set; }
        public int QtyPicked { get; set; }
        public int QtyAvaliable { get; set; }
        public int QtyExpected { get; set; }
        public int QtyPickInProcess { get; set; }
        [DefaultValue(0)]
        public int QtyOrder { get; set; }
        public int PendingMoveIN { get; set; }
        public int ArchiveQty { get; set; }
        public System.DateTime ArchiveDate { get; set; }
        public string Status { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddWho { get; set; }
        public System.DateTime EditDate { get; set; }
        public string EditWho { get; set; }
        public string TrafficCop { get; set; }
        public string ArchiveCop { get; set; }
        public Nullable<double> ArchiveGrossWgt { get; set; }
        public Nullable<double> ArchiveCube { get; set; }
        public string Lottable01 { get; set; }
        public string Lottable02 { get; set; }
        public string Lottable03 { get; set; }
        public string Lottable04 { get; set; }
        public string Lottable05 { get; set; }
        public string Lottable06 { get; set; }
        public string Lottable07 { get; set; }
        public string Lottable08 { get; set; }
        public string Lottable09 { get; set; }
        public string Lottable10 { get; set; }
        public string ImportEntry { get; set; }
        
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> NetWgt { get; set; }
        public Nullable<double> GrossWgt { get; set; }

        public string PcNo { get; set; }
    }
}
