//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSPortal.Core.Model
{
    using System;
    using System.Collections.Generic;
    using MicroOrm.Pocos.SqlGenerator.Attributes;
    [StoredAs("Sku")]
    public partial class Product
    {
        public Nullable<int> Gennumber { get; set; }
        public string StorerKey { get; set; }
        public string Sku { get; set; }
        public string HazMatCodesKey { get; set; }
        public string SUSR1 { get; set; }
        public string SUSR2 { get; set; }
        public string SUSR3 { get; set; }
        public string SUSR4 { get; set; }
        public string SUSR5 { get; set; }
        public string MANUFACTURERSKU { get; set; }
        public string DESCR { get; set; }
        public string RETAILSKU { get; set; }
        public string ALTSKU { get; set; }
        public string PACKKey { get; set; }
        public double STDGROSSWGT { get; set; }
        public double STDNETWGT { get; set; }
        public double STDCUBE { get; set; }
        public double TARE { get; set; }
        public string CLASS { get; set; }
        public string ACTIVE { get; set; }
        public string SKUGROUP { get; set; }
        public string Tariffkey { get; set; }
        public string BUSR1 { get; set; }
        public string BUSR2 { get; set; }
        public string BUSR3 { get; set; }
        public string BUSR4 { get; set; }
        public string BUSR5 { get; set; }
        public string LOTTABLE01LABEL { get; set; }
        public string LOTTABLE02LABEL { get; set; }
        public string LOTTABLE03LABEL { get; set; }
        public string LOTTABLE04LABEL { get; set; }
        public string LOTTABLE05LABEL { get; set; }
        public string LOTTABLE06LABEL { get; set; }
        public string LOTTABLE07LABEL { get; set; }
        public string LOTTABLE08LABEL { get; set; }
        public string LOTTABLE09LABEL { get; set; }
        public string LOTTABLE10LABEL { get; set; }
        public string NOTES1 { get; set; }
        public string NOTES2 { get; set; }
        public string PickCode { get; set; }
        public string StrategyKey { get; set; }
        public string CartonGroup { get; set; }
        public string PutCode { get; set; }
        public string PutawayLoc { get; set; }
        public string PutawayZone { get; set; }
        public int InnerPack { get; set; }
        public double Cube { get; set; }
        public double GrossWgt { get; set; }
        public double NetWgt { get; set; }
        public string ABC { get; set; }
        public Nullable<int> CycleCountFrequency { get; set; }
        public Nullable<System.DateTime> LastCycleCount { get; set; }
        public Nullable<int> ReorderPoint { get; set; }
        public Nullable<int> ReorderQty { get; set; }
        public Nullable<double> StdOrderCost { get; set; }
        public Nullable<double> CarryCost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string OnReceiptCopyPackkey { get; set; }
        public string ReceiptHoldCode { get; set; }
        public string ReceiptInspectionLoc { get; set; }
        public string RotateBy { get; set; }
        public Nullable<int> DateCodeDays { get; set; }
        public string DefaultRotation { get; set; }
        public string shippablecontainer { get; set; }
        public string IOFLAG { get; set; }
        public Nullable<decimal> TAREWEIGHT { get; set; }
        public string LOTXIDDETAILOTHERLABEL1 { get; set; }
        public string LOTXIDDETAILOTHERLABEL2 { get; set; }
        public string LOTXIDDETAILOTHERLABEL3 { get; set; }
        public Nullable<decimal> AVGCASEWEIGHT { get; set; }
        public Nullable<decimal> TOLERANCEPCT { get; set; }
        public string SHELFLIFEINDICATOR { get; set; }
        public Nullable<int> SHELFLIFE { get; set; }
        public string TRANSPORTATIONMODE { get; set; }
        public string SKUGROUP2 { get; set; }
        public string SUSR6 { get; set; }
        public string SUSR7 { get; set; }
        public string SUSR8 { get; set; }
        public string SUSR9 { get; set; }
        public string SUSR10 { get; set; }
        public string BUSR6 { get; set; }
        public string BUSR7 { get; set; }
        public string BUSR8 { get; set; }
        public string BUSR9 { get; set; }
        public string BUSR10 { get; set; }
        public decimal MinimumShelfLifeOnRFPicking { get; set; }
        public string FREIGHTCLASS { get; set; }
        public string ICWFlag { get; set; }
        public string ICWBy { get; set; }
        public string IDEWeight { get; set; }
        public string ICDFlag { get; set; }
        public string ICDLABEL1 { get; set; }
        public string ICDLABEL2 { get; set; }
        public string ICDLABEL3 { get; set; }
        public string OCWFLAG { get; set; }
        public string OCWBy { get; set; }
        public string ODEWeight { get; set; }
        public string OACOverride { get; set; }
        public string OCDFlag { get; set; }
        public string OCDLabel1 { get; set; }
        public string OCDLabel2 { get; set; }
        public string OCDLabel3 { get; set; }
        public Nullable<decimal> OTAREWEIGHT { get; set; }
        public Nullable<decimal> OAVGCASEWEIGHT { get; set; }
        public Nullable<decimal> OTOLERANCEPCT { get; set; }
        public string RFDefaultPack { get; set; }
        public string RFDefaultUOM { get; set; }
        public string SHELFLIFECODETYPE { get; set; }
        public int SHELFLIFEONRECEIVING { get; set; }
        public string LOTTABLEVALIDATIONKEY { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddWho { get; set; }
        public System.DateTime EditDate { get; set; }
        public string EditWho { get; set; }
        public string TrafficCop { get; set; }
        public string ArchiveCop { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> EffecStartDate { get; set; }
        public Nullable<System.DateTime> EffecEndDate { get; set; }
        public string Conveyable { get; set; }
        public string FlowThruItem { get; set; }
        public string BaseType { get; set; }
        public string MultiplePackkey { get; set; }
        public string ShelfLifeFlag { get; set; }
        public string ExpiryDateFlag { get; set; }
        public string WarrantyFlag { get; set; }
        public string NewSkuFlag { get; set; }
    }
}
