//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSPortal.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public Nullable<int> Gennumber { get; set; }
        public string WarehouseKey { get; set; }
        public string ReceiptKey { get; set; }
        public string ReceiptLineNumber { get; set; }
        public string ExternReceiptKey { get; set; }
        public string ExternLineNo { get; set; }
        public string WarehouseReference { get; set; }
        public string StorerKey { get; set; }
        public string StorerName { get; set; }
        public string PoKey { get; set; }
        public string tariffkey { get; set; }
        public string Sku { get; set; }
        public string SkuDescription { get; set; }
        public string AltSku { get; set; }
        public string Id { get; set; }
        public string Status { get; set; }
        public System.DateTime DateReceived { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int QtyExpected { get; set; }
        public int QtyAdjusted { get; set; }
        public int QtyReceived { get; set; }
        public string UOM { get; set; }
        public string PackKey { get; set; }
        public string VesselKey { get; set; }
        public string VoyageKey { get; set; }
        public string XdockKey { get; set; }
        public string ContainerKey { get; set; }
        public string ToLoc { get; set; }
        public string ToLot { get; set; }
        public string ToId { get; set; }
        public string ConditionCode { get; set; }
        public string Lottable01 { get; set; }
        public string Lottable02 { get; set; }
        public string Lottable03 { get; set; }
        public Nullable<System.DateTime> Lottable04 { get; set; }
        public Nullable<System.DateTime> Lottable05 { get; set; }
        public string Lottable06 { get; set; }
        public string Lottable07 { get; set; }
        public string Lottable08 { get; set; }
        public string Lottable09 { get; set; }
        public string Lottable10 { get; set; }
        public int CaseCnt { get; set; }
        public int InnerPack { get; set; }
        public int Pallet { get; set; }
        public double Cube { get; set; }
        public double GrossWgt { get; set; }
        public double NetWgt { get; set; }
        public double OtherUnit1 { get; set; }
        public double OtherUnit2 { get; set; }
        public double UnitPrice { get; set; }
        public double ExtendedPrice { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string forte_flag { get; set; }
        public string SUSR1 { get; set; }
        public string SUSR2 { get; set; }
        public string SUSR3 { get; set; }
        public string SUSR4 { get; set; }
        public string SUSR5 { get; set; }
        public string NOTES { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddWho { get; set; }
        public System.DateTime EditDate { get; set; }
        public string EditWho { get; set; }
        public string TrafficCop { get; set; }
        public string ArchiveCop { get; set; }
        public string ITRNSourceKey { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> Weight { get; set; }
        public string SUSR6 { get; set; }
        public string SUSR7 { get; set; }
        public string ExternTransactionId { get; set; }
        public string Attribute01 { get; set; }
        public string DistributionID { get; set; }
        public string CONDITION { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string Reference3 { get; set; }
        public string Reference4 { get; set; }
        public string Reference5 { get; set; }
        public string Reference6 { get; set; }
        public string Reference7 { get; set; }
        public string Reference8 { get; set; }
        public string Reference9 { get; set; }
        public string Reference10 { get; set; }
        public string PONumber { get; set; }
        public string TransmitFlag { get; set; }
        public string POLineNumber { get; set; }
        public string ExportGRECFlag { get; set; }
        public Nullable<decimal> QtyException1 { get; set; }
        public string ConditionCode2 { get; set; }
        public Nullable<int> QtyException2 { get; set; }
        public string ConditionCode3 { get; set; }
        public Nullable<int> QtyException3 { get; set; }
        public string ReceiptLineType { get; set; }
        public string Caseno { get; set; }
        public string CountryofOrigin { get; set; }
        public string HAWB { get; set; }
        public string Invoice { get; set; }
        public string Instruction { get; set; }
        public string LocationCategory1 { get; set; }
        public string LocationCategory2 { get; set; }
        public string LocationCategory3 { get; set; }
        public string ImportFlag { get; set; }
        public string ReceiptType { get; set; }
        public Nullable<decimal> UOMQty { get; set; }
        
    }
}
