//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSPortal.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storer
    {
        public Nullable<int> Gennumber { get; set; }
        public string StorerKey { get; set; }
        public string type { get; set; }
        public string Company { get; set; }
        public string VAT { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string ISOCntryCode { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string B_contact1 { get; set; }
        public string B_Contact2 { get; set; }
        public string B_Company { get; set; }
        public string B_Address1 { get; set; }
        public string B_Address2 { get; set; }
        public string B_Address3 { get; set; }
        public string B_Address4 { get; set; }
        public string B_City { get; set; }
        public string B_State { get; set; }
        public string B_Zip { get; set; }
        public string B_Country { get; set; }
        public string B_ISOCntryCode { get; set; }
        public string B_Phone1 { get; set; }
        public string B_Phone2 { get; set; }
        public string B_Fax1 { get; set; }
        public string B_Fax2 { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public string CreditLimit { get; set; }
        public string CartonGroup { get; set; }
        public string PickCode { get; set; }
        public string CreatePATaskOnRFReceipt { get; set; }
        public string CalculatePutAwayLocation { get; set; }
        public string Status { get; set; }
        public string DefaultStrategy { get; set; }
        public string DefaultSkuRotation { get; set; }
        public string DefaultRotation { get; set; }
        public string SCAC_CODE { get; set; }
        public string TITLE1 { get; set; }
        public string TITLE2 { get; set; }
        public string DESCRIPTION { get; set; }
        public string SUSR1 { get; set; }
        public string SUSR2 { get; set; }
        public string SUSR3 { get; set; }
        public string SUSR4 { get; set; }
        public string SUSR5 { get; set; }
        public string SUSR6 { get; set; }
        public string MultiZonePLPA { get; set; }
        public string CWOFlag { get; set; }
        public string ROLLRECEIPT { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddWho { get; set; }
        public System.DateTime EditDate { get; set; }
        public string EditWho { get; set; }
        public string TrafficCop { get; set; }
        public string ArchiveCop { get; set; }
        public Nullable<int> PaymentTerms { get; set; }
        public string SiteCode { get; set; }
        public string LocationCategory { get; set; }
        public string DespatchId { get; set; }
        public string S_Company { get; set; }
        public string S_Address1 { get; set; }
        public string S_address2 { get; set; }
        public string S_City { get; set; }
        public string S_Region { get; set; }
        public string S_Zip { get; set; }
        public string S_Country { get; set; }
        public string S_address3 { get; set; }
        public string S_address4 { get; set; }
        public string Instructions1 { get; set; }
        public string Instructions2 { get; set; }
        public string Instructions3 { get; set; }
    }
}
